### ISSUE TITLE
Bug: cannot read .env

### ISSUE THREAD

**Issue by geeks121** [Pycomet/EscrowService-Bot#4]
i have create .env config but the code not recognice the environment..
as example the database url ,, i have setup correct db url,, so i try edit to direct acces to db ,,

example :

`engine = create_engine("mysql+pymysql://root:root@localhost:3308")`
`#    os.getenv("DATABASE_URL"),`
`#    echo=False)`
`#    connect_args={'check_same_thread': False},`

commented os.getenv for trying ,, and try with engin = create_engine with url

and it worked for me,, the bug db gone .,, and now i have other error ,,

`Traceback (most recent call last):`
  `File "<frozen importlib._bootstrap>", line 991, in _find_and_load`
 ` File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked`
  `File "<frozen importlib._bootstrap>", line 671, in _load_unlocked`
  `File "<frozen importlib._bootstrap_external>", line 783, in exec_module`
  `File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed`
 ` File "C:\Users\HPs\Documents\escrow-service-bot\config.py", line 24, in <module>`
    `importdir.do("handlers", globals())`
  `File "C:\Users\HPs\Documents\escrow-service-bot\importdir.py", line 18, in do`
    `__do(path, env)`
  `File "C:\Users\HPs\Documents\escrow-service-bot\importdir.py", line 47, in __do`
    `env[module_name] = __import__(module_name)              # ... import`
  `File "handlers\callbacks.py", line 3, in <module>`
    `from functions import *`
  `File "C:\Users\HPs\Documents\escrow-service-bot\functions.py", line 9, in <module>`
   ` client = Client(API_KEY, API_SECRET)`
  `File "C:\Users\HPs\Documents\escrow-service-bot\env\lib\site-packages\coinbase\wallet\client.py", line 73, in __init__`
    `raise ValueError('Missing `api_key`.')`
`ValueError: Missing `api_key`.`

i have correct .env config for it .. and have setup env for doing this experiment

**Comment by Pycomet** [comment]
Okay

After starting the flask application, it attempts connecting to the coinbase API but is not possible because you have not added your API_KEY and API_SECRET from an authorized coinbase account

**Comment by geeks121** [comment]
that is strange .. i have add correct api key from coinbase account
