### ISSUE TITLE
Add feature : total transaction, escrow level

### ISSUE THREAD

**Issue by geeks121** [Pycomet/EscrowService-Bot#5]
Add total transaction command in bot and total amount in USD or other currency.

Escrow level :
Escrow star ,, when user seller and buyer hit 10+ transaction it hit 4 start ... and more ,, this is useful .. so seller can know their succes trade ,, not spammer who abusing seller time .. so the seller have choice ,, cancel or continue

banned : abusing system with 50 or under it in a row
when seller or buyer cancel trade more than 50 trade in a row the bot detected it is abusing system, then banned them

**Comment by Pycomet** [comment]
I even think the banning limit being at 50 is way too high. A buyer would be restricted from using the bot if they have up to 10 disputes on their trade

**Comment by Pycomet** [comment]
The user star feature is a good prospect. I will look forward to it after complete to new currencies I am adding to the bot. Also, I attached my crypto wallet address for donation as requested

**Comment by Pycomet** [comment]
Thanks

**Comment by geeks121** [comment]
if 50 dispute is higher ,,
then split banned into 3 option

warning 10 cancelled trade or less from it

if hit 30 soft banned ,, banned in 3 day 7 day or more day 

permanen banned this is the bot owner option if hit 50 or more ,,, must contact admin ,, and admin can unbanned using command if the abuser promise to use bot with succes trade.

all banned level is based on cancelled order in arrow.

going to donate litle money bro

**Comment by geeks121** [comment]
add dogecoin wallet bro :D if you wish

**Comment by geeks121** [comment]
please add my local currency too ,, my local currency is IDR - Indonesia Rupiah
