### ISSUE TITLE
sqlalchemy not create db & table anymore

### ISSUE THREAD

**Issue by geeks121** [Pycomet/EscrowService-Bot#6]
i have tried with postgresql, mysql ,, all error is same ,, the error log i found in heroku app ,, also i run in vps have same error ,, 
any suggest?

can you add db.create_all to automatically create table 

Jul 03 00:20:49 zapber-telebot app/web.1 The above exception was the direct cause of the following exception:
Jul 03 00:20:49 zapber-telebot app/web.1 
Jul 03 00:20:49 zapber-telebot app/web.1 Traceback (most recent call last):
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/telebot/util.py", line 60, in run
Jul 03 00:20:49 zapber-telebot app/web.1     task(*args, **kwargs)
Jul 03 00:20:49 zapber-telebot app/web.1   File "handlers/callbacks.py", line 18, in callback_answer
Jul 03 00:20:49 zapber-telebot app/web.1     start_seller(call)
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/bot.py", line 12, in start_seller
Jul 03 00:20:49 zapber-telebot app/web.1     user = get_user(msg=user)
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/functions.py", line 24, in get_user
Jul 03 00:20:49 zapber-telebot app/web.1     user = session.query(User).filter_by(id=id).first()
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3300, in first
Jul 03 00:20:49 zapber-telebot app/web.1     ret = list(self[0:1])
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3078, in __getitem__
Jul 03 00:20:49 zapber-telebot app/web.1     return list(res)
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
Jul 03 00:20:49 zapber-telebot app/web.1     return self._execute_and_instances(context)
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
Jul 03 00:20:49 zapber-telebot app/web.1     result = conn.execute(querycontext.statement, self._params)
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
Jul 03 00:20:49 zapber-telebot app/web.1     return meth(self, multiparams, params)
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
Jul 03 00:20:49 zapber-telebot app/web.1     return connection._execute_clauseelement(self, multiparams, params)
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
Jul 03 00:20:49 zapber-telebot app/web.1     distilled_params,
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
Jul 03 00:20:49 zapber-telebot app/web.1     e, statement, parameters, cursor, context
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
Jul 03 00:20:49 zapber-telebot app/web.1     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
Jul 03 00:20:49 zapber-telebot app/web.1     raise exception
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
Jul 03 00:20:49 zapber-telebot app/web.1     cursor, statement, parameters, context
Jul 03 00:20:49 zapber-telebot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
Jul 03 00:20:49 zapber-telebot app/web.1     cursor.execute(statement, parameters)
Jul 03 00:20:49 zapber-telebot app/web.1 sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "users" does not exist
Jul 03 00:20:49 zapber-telebot app/web.1 LINE 2: FROM users

**Comment by geeks121** [comment]
solved 

uncomment create_all 


and add string lenght please,, because the database will error without string lenght ,, i don't know best formula to string ,, stil facing error when select local currency

**Comment by Ola-Daniel** [comment]
Can you check, still facing this same error

**Comment by Ola-Daniel** [comment]
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(9)

[SQL: INSERT INTO users (id, chat) VALUES (%(id)s, %(chat)s)]
[parameters: {'id': 2062079191, 'chat': 2062079191}]
(Background on this error at: http://sqlalche.me/e/9h9h

**Comment by geeks121** [comment]
for the lenght you may check another branch to setup the lenght ,,
