### ISSUE TITLE
is:Seller & buyer in same account :bug

### ISSUE THREAD

**Issue by geeks121** [Pycomet/EscrowService-Bot#8]
Same account can create seller id and become buyer to join that id ,, this is bug ..

and the price can be null like the screenshot:

![bug](https://user-images.githubusercontent.com/16743443/86766986-8008fa00-c075-11ea-9f67-a2aa209d9f22.PNG)

check my donation to your dogecoin too

**Comment by Pycomet** [comment]
I already fixed the issue that caused this to the bot. You users can not access the same trade being the buyer and seller at once... And certainly led to that user's account being banned from this service
